import { ClinicalNote, ClinicalDocument, NoteTemplate, ClinicalStats } from '../types/clinical';

export const mockClinicalNotes: ClinicalNote[] = [
  {
    id: 'NOTE-001',
    patientId: 'P001',
    patientName: 'John Smith',
    authorId: 'S001',
    authorName: 'Dr. Sarah Johnson',
    date: '2024-01-15',
    type: 'admission',
    category: 'Emergency',
    title: 'Emergency Admission - Ankle Fracture',
    content: 'Patient presented with acute ankle pain after fall. X-ray confirms fracture of lateral malleolus. Pain level 7/10. Vitals stable. Treatment plan includes immobilization and pain management.',
    status: 'final',
    lastModified: '2024-01-15T14:30:00Z',
    department: 'Emergency',
    tags: ['fracture', 'orthopedic', 'trauma'],
  },
  {
    id: 'NOTE-002',
    patientId: 'P002',
    patientName: 'Sarah Johnson',
    authorId: 'S002',
    authorName: 'Dr. Michael Chen',
    date: '2024-01-20',
    type: 'procedure',
    category: 'Surgery',
    title: 'Laparoscopic Appendectomy',
    content: 'Procedure completed successfully without complications. Patient tolerated procedure well. Appendix removed intact. No signs of perforation. Estimated blood loss: 50ml. Patient transferred to recovery.',
    status: 'final',
    lastModified: '2024-01-20T16:45:00Z',
    department: 'Surgery',
    tags: ['surgery', 'appendectomy', 'laparoscopic'],
  },
  {
    id: 'NOTE-003',
    patientId: 'P003',
    patientName: 'Michael Brown',
    authorId: 'S004',
    authorName: 'Dr. James Wilson',
    date: '2024-02-01',
    type: 'consultation',
    category: 'Neurology',
    title: 'Headache Consultation',
    content: 'Patient reports persistent headaches for 2 weeks. No neurological deficits on examination. MRI ordered to rule out structural abnormalities. Current medications reviewed. Follow-up scheduled.',
    status: 'final',
    lastModified: '2024-02-01T10:15:00Z',
    department: 'Neurology',
    tags: ['headache', 'neurology', 'consultation'],
  },
  {
    id: 'NOTE-004',
    patientId: 'P004',
    patientName: 'Emily Davis',
    authorId: 'S003',
    authorName: 'Nurse Emily Davis',
    date: '2024-01-05',
    type: 'progress',
    category: 'ICU',
    title: 'ICU Progress Note - Day 2',
    content: 'Patient showing improvement. Respiratory rate normalized. Oxygen saturation 95% on room air. Alert and oriented. Diet advanced as tolerated. Continue current treatment plan.',
    status: 'final',
    lastModified: '2024-01-05T08:00:00Z',
    department: 'ICU',
    tags: ['icu', 'progress', 'respiratory'],
  },
  {
    id: 'NOTE-005',
    patientId: 'P005',
    patientName: 'Robert Wilson',
    authorId: 'S004',
    authorName: 'Dr. James Wilson',
    date: '2024-02-10',
    type: 'general',
    category: 'Primary Care',
    title: 'Annual Physical Examination',
    content: 'Patient in good health. All vitals within normal range. Laboratory results reviewed - all normal. Immunizations up to date. Health maintenance counseling provided.',
    status: 'draft',
    lastModified: '2024-02-10T11:30:00Z',
    department: 'Primary Care',
    tags: ['physical', 'preventive', 'wellness'],
  },
];

export const mockClinicalDocuments: ClinicalDocument[] = [
  {
    id: 'DOC-001',
    patientId: 'P001',
    patientName: 'John Smith',
    title: 'Ankle X-Ray Results',
    type: 'radiology',
    category: 'Imaging',
    uploadDate: '2024-01-15',
    uploadedBy: 'Dr. Sarah Johnson',
    fileUrl: '/documents/xray-001.pdf',
    fileSize: 2048000,
    mimeType: 'application/pdf',
    tags: ['xray', 'fracture', 'orthopedic'],
    department: 'Radiology',
  },
  {
    id: 'DOC-002',
    patientId: 'P003',
    patientName: 'Michael Brown',
    title: 'Brain MRI Report',
    type: 'radiology',
    category: 'Imaging',
    uploadDate: '2024-02-02',
    uploadedBy: 'Dr. James Wilson',
    fileUrl: '/documents/mri-002.pdf',
    fileSize: 5120000,
    mimeType: 'application/pdf',
    tags: ['mri', 'brain', 'neurology'],
    department: 'Radiology',
  },
  {
    id: 'DOC-003',
    patientId: 'P005',
    patientName: 'Robert Wilson',
    title: 'Complete Blood Count',
    type: 'lab_result',
    category: 'Laboratory',
    uploadDate: '2024-02-10',
    uploadedBy: 'Lab Technician',
    fileUrl: '/documents/lab-003.pdf',
    fileSize: 512000,
    mimeType: 'application/pdf',
    tags: ['blood', 'lab', 'cbc'],
    department: 'Laboratory',
  },
  {
    id: 'DOC-004',
    patientId: 'P002',
    patientName: 'Sarah Johnson',
    title: 'Surgical Consent Form',
    type: 'consent_form',
    category: 'Consent',
    uploadDate: '2024-01-19',
    uploadedBy: 'Dr. Michael Chen',
    fileUrl: '/documents/consent-004.pdf',
    fileSize: 256000,
    mimeType: 'application/pdf',
    tags: ['consent', 'surgery', 'legal'],
    department: 'Surgery',
  },
  {
    id: 'DOC-005',
    patientId: 'P004',
    patientName: 'Emily Davis',
    title: 'Pathology Report',
    type: 'pathology',
    category: 'Laboratory',
    uploadDate: '2024-01-06',
    uploadedBy: 'Pathologist',
    fileUrl: '/documents/path-005.pdf',
    fileSize: 1024000,
    mimeType: 'application/pdf',
    tags: ['pathology', 'biopsy', 'lab'],
    department: 'Pathology',
  },
];

export const mockNoteTemplates: NoteTemplate[] = [
  {
    id: 'TPL-001',
    name: 'Progress Note',
    type: 'progress',
    category: 'General',
    content: 'Subjective:\nObjective:\nAssessment:\nPlan:',
    fields: [
      { id: 'subjective', label: 'Subjective', type: 'textarea', required: true, placeholder: 'Patient complaints and symptoms' },
      { id: 'objective', label: 'Objective', type: 'textarea', required: true, placeholder: 'Vital signs, examination findings' },
      { id: 'assessment', label: 'Assessment', type: 'textarea', required: true, placeholder: 'Diagnosis and evaluation' },
      { id: 'plan', label: 'Plan', type: 'textarea', required: true, placeholder: 'Treatment plan and next steps' },
    ],
  },
  {
    id: 'TPL-002',
    name: 'Admission Note',
    type: 'admission',
    category: 'Inpatient',
    content: 'Chief Complaint:\nHistory of Present Illness:\nPast Medical History:\nMedications:\nAllergies:\nPhysical Examination:\nAssessment and Plan:',
    fields: [
      { id: 'chief_complaint', label: 'Chief Complaint', type: 'text', required: true, placeholder: 'Primary reason for admission' },
      { id: 'hpi', label: 'History of Present Illness', type: 'textarea', required: true, placeholder: 'Detailed history' },
      { id: 'pmh', label: 'Past Medical History', type: 'textarea', required: false, placeholder: 'Previous conditions' },
      { id: 'medications', label: 'Medications', type: 'textarea', required: false, placeholder: 'Current medications' },
      { id: 'allergies', label: 'Allergies', type: 'text', required: true, placeholder: 'Known allergies' },
      { id: 'physical_exam', label: 'Physical Examination', type: 'textarea', required: true, placeholder: 'Examination findings' },
      { id: 'assessment_plan', label: 'Assessment and Plan', type: 'textarea', required: true, placeholder: 'Initial assessment and treatment plan' },
    ],
  },
  {
    id: 'TPL-003',
    name: 'Discharge Summary',
    type: 'discharge',
    category: 'Inpatient',
    content: 'Admission Date:\nDischarge Date:\nDiagnosis:\nProcedures:\nHospital Course:\nDischarge Medications:\nFollow-up Instructions:',
    fields: [
      { id: 'admission_date', label: 'Admission Date', type: 'date', required: true },
      { id: 'discharge_date', label: 'Discharge Date', type: 'date', required: true },
      { id: 'diagnosis', label: 'Diagnosis', type: 'textarea', required: true, placeholder: 'Primary and secondary diagnoses' },
      { id: 'procedures', label: 'Procedures', type: 'textarea', required: false, placeholder: 'Procedures performed' },
      { id: 'hospital_course', label: 'Hospital Course', type: 'textarea', required: true, placeholder: 'Summary of hospital stay' },
      { id: 'discharge_meds', label: 'Discharge Medications', type: 'textarea', required: true, placeholder: 'Medications prescribed at discharge' },
      { id: 'followup', label: 'Follow-up Instructions', type: 'textarea', required: true, placeholder: 'Follow-up appointments and instructions' },
    ],
  },
];

export const mockClinicalStats: ClinicalStats = {
  totalNotes: 1247,
  notesChange: 8.5,
  totalDocuments: 856,
  documentsChange: 12.3,
  pendingReviews: 23,
  reviewsChange: -15.2,
  averageCompletionTime: 18.5,
  timeChange: -7.8,
};
