import { StaffMember, Department, Shift, PerformanceMetric, StaffStats } from '../types/staff';

export const mockStaffMembers: StaffMember[] = [
  {
    id: 'S001',
    employeeId: 'EMP-001',
    firstName: 'Sarah',
    lastName: 'Johnson',
    fullName: 'Dr. Sarah Johnson',
    email: 'sarah.johnson@hospital.com',
    phone: '+1-555-0101',
    role: 'Emergency Physician',
    department: 'Emergency',
    specialization: 'Emergency Medicine',
    hireDate: '2018-03-15',
    status: 'active',
    certifications: [
      {
        id: 'CERT-001',
        name: 'Board Certified - Emergency Medicine',
        issuingOrganization: 'American Board of Emergency Medicine',
        issueDate: '2019-01-10',
        expiryDate: '2029-01-10',
        credentialId: 'ABEM-2019-12345',
      },
      {
        id: 'CERT-002',
        name: 'ACLS Certification',
        issuingOrganization: 'American Heart Association',
        issueDate: '2023-06-15',
        expiryDate: '2025-06-15',
        credentialId: 'AHA-ACLS-45678',
      },
    ],
    address: '123 Medical Drive, Boston, MA 02115',
  },
  {
    id: 'S002',
    employeeId: 'EMP-002',
    firstName: 'Michael',
    lastName: 'Chen',
    fullName: 'Dr. Michael Chen',
    email: 'michael.chen@hospital.com',
    phone: '+1-555-0102',
    role: 'Surgeon',
    department: 'Surgery',
    specialization: 'General Surgery',
    hireDate: '2016-07-01',
    status: 'active',
    certifications: [
      {
        id: 'CERT-003',
        name: 'Board Certified - General Surgery',
        issuingOrganization: 'American Board of Surgery',
        issueDate: '2017-08-20',
        expiryDate: '2027-08-20',
        credentialId: 'ABS-2017-67890',
      },
    ],
    address: '456 Healthcare Ave, Boston, MA 02116',
  },
  {
    id: 'S003',
    employeeId: 'EMP-003',
    firstName: 'Emily',
    lastName: 'Davis',
    fullName: 'Nurse Emily Davis',
    email: 'emily.davis@hospital.com',
    phone: '+1-555-0103',
    role: 'Registered Nurse',
    department: 'ICU',
    specialization: 'Critical Care',
    hireDate: '2019-02-10',
    status: 'active',
    certifications: [
      {
        id: 'CERT-004',
        name: 'Registered Nurse License',
        issuingOrganization: 'Massachusetts Board of Nursing',
        issueDate: '2018-12-01',
        expiryDate: '2026-12-01',
        credentialId: 'RN-MA-98765',
      },
      {
        id: 'CERT-005',
        name: 'Critical Care Nursing Certification',
        issuingOrganization: 'AACN',
        issueDate: '2020-05-15',
        expiryDate: '2023-05-15',
        credentialId: 'CCRN-54321',
      },
    ],
    address: '789 Nursing Blvd, Cambridge, MA 02138',
  },
  {
    id: 'S004',
    employeeId: 'EMP-004',
    firstName: 'James',
    lastName: 'Wilson',
    fullName: 'Dr. James Wilson',
    email: 'james.wilson@hospital.com',
    phone: '+1-555-0104',
    role: 'Pediatrician',
    department: 'Pediatrics',
    specialization: 'General Pediatrics',
    hireDate: '2017-09-01',
    status: 'active',
    certifications: [
      {
        id: 'CERT-006',
        name: 'Board Certified - Pediatrics',
        issuingOrganization: 'American Board of Pediatrics',
        issueDate: '2018-10-01',
        expiryDate: '2028-10-01',
        credentialId: 'ABP-2018-11223',
      },
    ],
    address: '321 Children Way, Brookline, MA 02445',
  },
  {
    id: 'S005',
    employeeId: 'EMP-005',
    firstName: 'Robert',
    lastName: 'Brown',
    fullName: 'Nurse Robert Brown',
    email: 'robert.brown@hospital.com',
    phone: '+1-555-0105',
    role: 'Registered Nurse',
    department: 'Emergency',
    hireDate: '2020-01-15',
    status: 'active',
    certifications: [
      {
        id: 'CERT-007',
        name: 'Registered Nurse License',
        issuingOrganization: 'Massachusetts Board of Nursing',
        issueDate: '2019-11-20',
        expiryDate: '2027-11-20',
        credentialId: 'RN-MA-87654',
      },
    ],
    address: '654 Emergency St, Somerville, MA 02143',
  },
  {
    id: 'S006',
    employeeId: 'EMP-006',
    firstName: 'Lisa',
    lastName: 'Anderson',
    fullName: 'Dr. Lisa Anderson',
    email: 'lisa.anderson@hospital.com',
    phone: '+1-555-0106',
    role: 'Obstetrician',
    department: 'Maternity',
    specialization: 'Obstetrics and Gynecology',
    hireDate: '2015-04-20',
    status: 'on_leave',
    certifications: [
      {
        id: 'CERT-008',
        name: 'Board Certified - OB/GYN',
        issuingOrganization: 'American Board of Obstetrics and Gynecology',
        issueDate: '2016-06-15',
        expiryDate: '2026-06-15',
        credentialId: 'ABOG-2016-33445',
      },
    ],
    address: '987 Maternity Lane, Newton, MA 02458',
  },
];

export const mockDepartments: Department[] = [
  {
    id: 'DEPT-001',
    name: 'Emergency',
    code: 'EMERG',
    head: 'Dr. Sarah Johnson',
    staffCount: 45,
    description: 'Emergency Department providing 24/7 acute care',
  },
  {
    id: 'DEPT-002',
    name: 'Surgery',
    code: 'SURG',
    head: 'Dr. Michael Chen',
    staffCount: 32,
    description: 'Surgical department with multiple operating rooms',
  },
  {
    id: 'DEPT-003',
    name: 'ICU',
    code: 'ICU',
    head: 'Dr. Patricia Martinez',
    staffCount: 28,
    description: 'Intensive Care Unit for critical patients',
  },
  {
    id: 'DEPT-004',
    name: 'Pediatrics',
    code: 'PEDS',
    head: 'Dr. James Wilson',
    staffCount: 38,
    description: 'Pediatric care for infants, children, and adolescents',
  },
  {
    id: 'DEPT-005',
    name: 'Maternity',
    code: 'MAT',
    head: 'Dr. Lisa Anderson',
    staffCount: 25,
    description: 'Maternity and obstetric services',
  },
];

export const mockShifts: Shift[] = [
  {
    id: 'SHIFT-001',
    staffId: 'S001',
    staffName: 'Dr. Sarah Johnson',
    department: 'Emergency',
    startTime: '2024-02-15T07:00:00Z',
    endTime: '2024-02-15T15:00:00Z',
    shiftType: 'morning',
    status: 'completed',
    location: 'Emergency Department',
    notes: 'Busy shift with 32 patients',
  },
  {
    id: 'SHIFT-002',
    staffId: 'S002',
    staffName: 'Dr. Michael Chen',
    department: 'Surgery',
    startTime: '2024-02-15T08:00:00Z',
    endTime: '2024-02-15T18:00:00Z',
    shiftType: 'morning',
    status: 'completed',
    location: 'Operating Room 1',
    notes: '3 scheduled surgeries completed',
  },
  {
    id: 'SHIFT-003',
    staffId: 'S003',
    staffName: 'Nurse Emily Davis',
    department: 'ICU',
    startTime: '2024-02-15T15:00:00Z',
    endTime: '2024-02-15T23:00:00Z',
    shiftType: 'afternoon',
    status: 'completed',
    location: 'ICU Ward',
    notes: 'Monitored 6 critical patients',
  },
  {
    id: 'SHIFT-004',
    staffId: 'S004',
    staffName: 'Dr. James Wilson',
    department: 'Pediatrics',
    startTime: '2024-02-16T07:00:00Z',
    endTime: '2024-02-16T15:00:00Z',
    shiftType: 'morning',
    status: 'scheduled',
    location: 'Pediatrics Ward',
  },
  {
    id: 'SHIFT-005',
    staffId: 'S005',
    staffName: 'Nurse Robert Brown',
    department: 'Emergency',
    startTime: '2024-02-16T15:00:00Z',
    endTime: '2024-02-16T23:00:00Z',
    shiftType: 'afternoon',
    status: 'scheduled',
    location: 'Emergency Department',
  },
  {
    id: 'SHIFT-006',
    staffId: 'S003',
    staffName: 'Nurse Emily Davis',
    department: 'ICU',
    startTime: '2024-02-16T23:00:00Z',
    endTime: '2024-02-17T07:00:00Z',
    shiftType: 'night',
    status: 'scheduled',
    location: 'ICU Ward',
  },
];

export const mockPerformanceMetrics: PerformanceMetric[] = [
  {
    staffId: 'S001',
    staffName: 'Dr. Sarah Johnson',
    department: 'Emergency',
    role: 'Emergency Physician',
    patientsHandled: 156,
    averageRating: 4.7,
    tasksCompleted: 142,
    attendanceRate: 98.5,
    punctualityScore: 95.0,
    period: '2024-01',
  },
  {
    staffId: 'S002',
    staffName: 'Dr. Michael Chen',
    department: 'Surgery',
    role: 'Surgeon',
    patientsHandled: 89,
    averageRating: 4.9,
    tasksCompleted: 85,
    attendanceRate: 100.0,
    punctualityScore: 98.0,
    period: '2024-01',
  },
  {
    staffId: 'S003',
    staffName: 'Nurse Emily Davis',
    department: 'ICU',
    role: 'Registered Nurse',
    patientsHandled: 203,
    averageRating: 4.6,
    tasksCompleted: 198,
    attendanceRate: 96.0,
    punctualityScore: 92.0,
    period: '2024-01',
  },
  {
    staffId: 'S004',
    staffName: 'Dr. James Wilson',
    department: 'Pediatrics',
    role: 'Pediatrician',
    patientsHandled: 178,
    averageRating: 4.8,
    tasksCompleted: 165,
    attendanceRate: 99.0,
    punctualityScore: 96.0,
    period: '2024-01',
  },
  {
    staffId: 'S005',
    staffName: 'Nurse Robert Brown',
    department: 'Emergency',
    role: 'Registered Nurse',
    patientsHandled: 189,
    averageRating: 4.5,
    tasksCompleted: 180,
    attendanceRate: 94.0,
    punctualityScore: 90.0,
    period: '2024-01',
  },
  {
    staffId: 'S006',
    staffName: 'Dr. Lisa Anderson',
    department: 'Maternity',
    role: 'Obstetrician',
    patientsHandled: 134,
    averageRating: 4.9,
    tasksCompleted: 128,
    attendanceRate: 97.0,
    punctualityScore: 94.0,
    period: '2024-01',
  },
];

export const mockStaffStats: StaffStats = {
  totalStaff: 168,
  staffChange: 5.3,
  activeShifts: 42,
  shiftsChange: 8.2,
  averagePerformance: 4.73,
  performanceChange: 3.5,
  vacancyRate: 8.5,
  vacancyChange: -12.0,
};
