apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: default
data:
  redis-host: "redis-service"
  redis-port: "6379"
  log-level: "info"
  audit-retention-days: "90"
  prometheus-metrics-port: "9464"
